name: Trigger auto deployment for todo-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ development ]
    paths:
    - '**'
    - '.github/workflows/todo-backend-AutoDeployTrigger-b7f2946e-9246-4d50-bac5-4443273c1241.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TODOBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TODOBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TODOBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: adintegrationtest.azurecr.io
          registryUsername: ${{ secrets.TODOBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TODOBACKEND_REGISTRY_PASSWORD }}
          containerAppName: todo-backend
          resourceGroup: AD-Integration-Test
          imageToBuild: adintegrationtest.azurecr.io/todo-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


